// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8BsRklR2OxICw4eW_0GucKLdSC0SfGWM',
    appId: '1:921219036496:web:e6b7c01d95f4241c1e6855',
    messagingSenderId: '921219036496',
    projectId: 'mantenciones-ingeterm',
    authDomain: 'mantenciones-ingeterm.firebaseapp.com',
    storageBucket: 'mantenciones-ingeterm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPc97DVMHw9FipvWx0vch-4i1rSdEOI64',
    appId: '1:476571441038:android:281cab2060b96dc51076df',
    messagingSenderId: '476571441038',
    projectId: 'mantencion-valvulas',
    storageBucket: 'mantencion-valvulas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGjPWmMRSRd1feHkvrJxh2R6sfxGTjKVc',
    appId: '1:476571441038:ios:1032da9ccab732041076df',
    messagingSenderId: '476571441038',
    projectId: 'mantencion-valvulas',
    storageBucket: 'mantencion-valvulas.firebasestorage.app',
    iosBundleId: 'com.example.mantencionValvulas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGjPWmMRSRd1feHkvrJxh2R6sfxGTjKVc',
    appId: '1:476571441038:ios:1032da9ccab732041076df',
    messagingSenderId: '476571441038',
    projectId: 'mantencion-valvulas',
    storageBucket: 'mantencion-valvulas.firebasestorage.app',
    iosBundleId: 'com.example.mantencionValvulas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxr7Rm3GNU3qAIkKbXmJXxUmOl9Rh6MEU',
    appId: '1:476571441038:web:92444efb67b7c2011076df',
    messagingSenderId: '476571441038',
    projectId: 'mantencion-valvulas',
    authDomain: 'mantencion-valvulas.firebaseapp.com',
    storageBucket: 'mantencion-valvulas.firebasestorage.app',
    measurementId: 'G-2YQCQ4DW83',
  );

}